spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://ec2-174-129-255-59.compute-1.amazonaws.com:5432/d8bv071jfptf3r
    username: ekqiwyjyskhsae
    password: 7923469eee42a46fc9e0db55831713ee8a422a0c15d2f639a071191300d73f99
#    jdbc-url: jdbc:postgresql://sqlvhnegrisoli.ddns.net:5432/dge_bi
#    jdbc-url: jdbc:postgresql://localhost:5432/dge_bi
#    username: postgres
#    password: 1y5h8j
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql

  jackson:
    time-zone: America/Sao_Paulo

  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob.non_contextual_creation: true

oauth-clients:
  projeto_mvp_app:
    client: dge_bi-client
    secret: dge_bi-secret

server:
  port: 8080

